"""
CSV export functionality for the FZU announcement crawler.

This module provides functions to export announcement data to CSV format using pandas.
"""
from pathlib import Path

import pandas as pd

from fzu_jxtz_crawler.models import Attachment, AnnouncementEntry
from fzu_jxtz_crawler.text_utils import clean_text


def _build_row_dict(
    entry: AnnouncementEntry,
    title: str | None,
    issuer: str | None,
    body: str | None,
    attachment_count: int,
    attachment: Attachment | None = None
) -> dict[str, str | int | None]:
    """
    Build a row dictionary for DataFrame export.
    
    Args:
        entry: The announcement entry
        title: Cleaned title text
        issuer: Cleaned issuer text
        body: Cleaned body text
        attachment_count: Number of attachments
        attachment: Optional attachment object. If None, empty strings are used for attachment fields
        
    Returns:
        Dictionary representing a single row in the DataFrame
    """
    row: dict[str, str | int | None] = {
        "id": entry.announcement_id,
        "url": entry.url,
        "title": title if title else "",
        "issuer": issuer if issuer else "",
        "pub_date": entry.pub_date.strftime("%Y-%m-%d"),
        "body": body if body else "",
        "attachment_count": attachment_count,
    }
    
    # Map CSV column names to Attachment attribute names
    attachment_fields = {
        "attachment_id": "attachment_id",
        "attachment_name": "name",
        "attachment_download_times": "download_times",
        "attachment_url": "url",
        "attachment_file_code": "file_code",
        "attachment_owner": "owner_code"
    }
    
    # Add attachment fields with values from attachment object or empty strings
    row.update({
        field: getattr(attachment, attr, "") if attachment else ""
        for field, attr in attachment_fields.items()
    })
    
    return row


def entries_to_dataframe(
    entries: list[AnnouncementEntry],
    clean_text_fields: bool = True
) -> pd.DataFrame:
    """
    Convert announcement entries to a pandas DataFrame.
    
    Args:
        entries: List of AnnouncementEntry objects
        clean_text_fields: If True, apply text cleaning to all text fields
        
    Returns:
        DataFrame with columns: url, title, issuer, pub_date, body,
        attachment_count, attachment_names
    """
    data: list[dict[str, str | int | None]] = []
    
    for entry in entries:
        # Apply text cleaning if requested
        title = clean_text(entry.title) if clean_text_fields and entry.title else entry.title
        issuer = clean_text(entry.issuer) if clean_text_fields and entry.issuer else entry.issuer
        body = clean_text(entry.body) if clean_text_fields and entry.body else entry.body
        
        # Extract attachment information
        # attachment_count = len(entry.attachments) if entry.attachments else 0
        # attachment_names = ""
        # if entry.attachments:
        #     names = [att.name for att in entry.attachments]
        #     attachment_names = "; ".join(names)
        #     if clean_text_fields:
        #         attachment_names = clean_text(attachment_names)

        attachment_count = len(entry.attachments) if entry.attachments else 0

        if attachment_count > 0:
            assert entry.attachments is not None, "Ahhh... How did we get here?"
            for attachment in entry.attachments:
                data.append(_build_row_dict(entry, title, issuer, body, attachment_count, attachment))
        else:
            data.append(_build_row_dict(entry, title, issuer, body, attachment_count))
    
    return pd.DataFrame(data)



def export_to_csv(
    entries: list[AnnouncementEntry],
    filepath: str | Path,
    clean_text_fields: bool = True
) -> None:
    """
    Export announcement entries to CSV file.
    
    Args:
        entries: List of AnnouncementEntry objects to export
        filepath: Path to the output CSV file
        clean_text_fields: If True, apply text cleaning to all text fields

    ( The following docs is completely generated by gpt-5.2 without human review )
    
    Column order:
        1) id (string)
            AnnouncementEntry.announcement_id
            12-character identifier: zfill6(tree_id) + zfill6(news_id)
            Example: "001036014278"
            IMPORTANT: must be read as string to preserve leading zeros.

        2) url (string)
            AnnouncementEntry.url
            Example: "https://jwch.fzu.edu.cn/info/1040/14402.htm"

        3) title (string)
            AnnouncementEntry.title
            Empty string if missing.

        4) issuer (string)
            AnnouncementEntry.issuer
            Empty string if missing.

        5) pub_date (date)
            AnnouncementEntry.pub_date formatted as "YYYY-MM-DD" (export-time string)
            Recommended read as datetime via parse_dates=["pub_date"].

        6) body (string)
            AnnouncementEntry.body
            Empty string if missing (crawler not fetched detail yet or no body).

        7) attachment_count (Int64)
            Number of attachments in the announcement (0 if none).

    Optional attachment fields (present only in "flattened attachments" exports,
    i.e., one row per attachment; announcement fields are repeated per attachment):
        8)  attachment_id (string)
            Attachment.attachment_id
            22-character identifier: zfill12(owner_code) + zfill10(file_code)
            IMPORTANT: must be read as string to preserve leading zeros.

        9)  attachment_name (string)
            Attachment.name

        10) attachment_download_times (Int64)
            Attachment.download_times

        11) attachment_url (string)
            Attachment.url

        12) attachment_file_code (string)
            Attachment.file_code (may contain leading zeros)

        13) attachment_owner (string)
            Attachment.owner_code (may contain leading zeros)

    Missing value convention:
        - Text fields may be exported as empty string "" when missing.
        - Integer count fields should be left empty (or omitted) if unknown; prefer using
          pandas nullable integer dtype "Int64" to support missing values.

    Recommended pandas read_csv configuration:
        dtype = {
            # IDs / codes (preserve leading zeros)
            "id": "string",
            "attachment_id": "string",
            "attachment_file_code": "string",
            "attachment_owner": "string",

            # text
            "url": "string",
            "title": "string",
            "issuer": "string",
            "body": "string",
            "attachment_name": "string",
            "attachment_url": "string",

            # counts (nullable ints)
            "attachment_count": "Int64",
            "attachment_download_times": "Int64",
        }
        parse_dates = ["pub_date"]

    Example:
        df = pd.read_csv("out.csv", dtype=dtype, parse_dates=["pub_date"])
    }

    """
    df = entries_to_dataframe(entries, clean_text_fields=clean_text_fields)
    
    # Export to CSV with proper line ending handling
    df.to_csv(
        filepath,
        index=False,
        encoding="utf-8",
        lineterminator="\n"  # Force LF line endings
    )
